// <auto-generated />
namespace Airlines.Business.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_table_useractivity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_table_useractivity));
        
        string IMigrationMetadata.Id
        {
            get { return "201803180721401_fix_table_useractivity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
